-- Sport Category
INSERT INTO categories (`title`, `description`) VALUES
('Sport', 'Questions about sport events, players and general sport rules');

-- Questions in sport category
INSERT INTO questions (`text`, `answer`, `category_id`) VALUES
('Lionel Messi has played his entire professional career at FC Barcelona', FALSE, 1),
('The Tour de France takes place every year in Spain', FALSE, 1),
('Serena Williams has won more Grand Slam titles than her sister Venus Williams', TRUE, 1),
('Michael Phelps is the most decorated Olympic athlete of all time', TRUE, 1),
('A football (soccer) match normally lasts 90 minutes', TRUE, 1),
('A handball team has 11 players on the court', FALSE, 1),
('Cristiano Ronaldo has played for both Manchester United and Real Madrid', TRUE, 1),
('Denmark won the UEFA European Championship in 1992', TRUE, 1),
('The Olympic Games are held every two years', FALSE, 1),
('A basketball hoop is 3.05 meters high', TRUE, 1),
('Roger Federer is from Switzerland', TRUE, 1),
('Formula 1 cars run on gasoline', TRUE, 1),
('A marathon is 42.195 kilometers long', TRUE, 1),
('Badminton was invented in Denmark', FALSE, 1),
('A golf ball typically has around 336 dimples', TRUE, 1),
('Wayne Gretzky is considered one of the greatest hockey players ever', TRUE, 1),
('The Tour de France always consists of 21 stages', FALSE, 1),
('A football player can be sent off with a yellow card', FALSE, 1),
('A strike in bowling means knocking down all 10 pins on the first throw', TRUE, 1),
('Caroline Wozniacki has been ranked world number one in tennis', TRUE, 1),
('The NFL is the American baseball league', FALSE, 1),
('The Olympic rings represent five continents', TRUE, 1),
('Danish cyclist Jonas Vingegaard has won the Tour de France', TRUE, 1),
('An ice hockey team has five players and one goalkeeper on the ice', TRUE, 1),
('In rugby, the ball is usually kicked forward', FALSE, 1),
('A basketball game has four quarters', TRUE, 1),
('In tennis, there are always three balls in play', FALSE, 1),
('Michael Jordan played for the Chicago Bulls', TRUE, 1),
('A hat trick in football means scoring three goals in one match', TRUE, 1),
('An Olympic gold medal is made of 100% gold', FALSE, 1),
('There is only one Grand Slam tournament in tennis', FALSE, 1),
('Manchester United plays its home games at Old Trafford', TRUE, 1),
('A baseball game can end in a draw', FALSE, 1),
('Denmark has won the World Championship in handball', TRUE, 1),
('A hockey goalie may use their hands to stop the puck', TRUE, 1),
('In cricket, the player who bowls the ball is called a “bowler”', TRUE, 1),
('A tennis match is always best of three sets', FALSE, 1),
('The Olympic Games were originally held in ancient Rome', FALSE, 1),
('LeBron James has played for the Los Angeles Lakers', TRUE, 1),
('In football, players may handle the ball if they are the goalkeeper', TRUE, 1),
('A triathlon consists of swimming, cycling, and running', TRUE, 1),
('Denmark has won Olympic gold in badminton', TRUE, 1),
('The Tour de France was first held in 1903', TRUE, 1),
('A handball court is 40 meters long', TRUE, 1),
('A football referee can show a red card', TRUE, 1),
('There are seven players on each handball team on the court', TRUE, 1),
('A penalty in hockey is the same as a free kick in football', FALSE, 1),
('A standard golf course has 18 holes', TRUE, 1),
('Volleyball is played with the feet', FALSE, 1),
('Lionel Messi has won the World Cup with Argentina', TRUE, 1),
('A ski jump is judged by both distance and style', TRUE, 1),
('A baseball bat is made of metal or wood', TRUE, 1),
('In American football, a touchdown is worth six points', TRUE, 1),
('A tennis player must win four points to win a game', TRUE, 1),
('The 2024 Olympic Games will be held in Paris', TRUE, 1),
('A yellow card in handball means two minutes of suspension', FALSE, 1),
('A Formula 1 track is also called a “circuit”', TRUE, 1),
('A dartboard has 20 numbered sections', TRUE, 1),
('In table tennis, the ball may bounce twice before being returned', FALSE, 1),
('A boxing match can only be won by knockout', FALSE, 1),
('A hockey goal counts as one point', TRUE, 1),
('A golfer tries to use as few strokes as possible', TRUE, 1),
('A frisbee is used in the sport called ultimate', TRUE, 1),
('An Olympic season lasts one month', FALSE, 1),
('Ice hockey games are played in three periods', TRUE, 1),
('In basketball, a shot can score 1, 2, or 3 points', TRUE, 1),
('An “ace” in tennis means the opponent doesn’t touch the ball', TRUE, 1),
('Lionel Messi has played for Paris Saint-Germain', TRUE, 1),
('A handball weighs around 500 grams', TRUE, 1),
('Cyclists are not allowed to draft behind another rider', FALSE, 1),
('A tennis match can end in a draw', FALSE, 1),
('The FIFA World Cup is held every four years', TRUE, 1),
('Offside occurs when a player is closer to the goal than the ball and the second-last defender', TRUE, 1),
('A basketball game can go into overtime', TRUE, 1),
('A football goal is 7.32 meters wide', TRUE, 1),
('A marathon is named after a Greek city', TRUE, 1),
('A boxer wears gloves during a match', TRUE, 1),
('In swimming, fins are not allowed in competitions', TRUE, 1),
('Denmark has won Olympic gold in sailing', TRUE, 1),
('A golfer uses clubs, not rackets', TRUE, 1),
('A red card in football means ejection from the game', TRUE, 1),
('A handball player can take three steps without dribbling', TRUE, 1),
('The Olympic symbols were designed by Pierre de Coubertin', TRUE, 1),
('A football must have a circumference of 68–70 cm', TRUE, 1),
('A 400-meter sprinter runs under 10 seconds', FALSE, 1),
('A cyclist can win a stage without winning the entire race', TRUE, 1),
('Michael Schumacher has won the Formula 1 World Championship', TRUE, 1),
('A table tennis game is usually played to 11 points', TRUE, 1),
('A swimmer may start before the start signal', FALSE, 1),
('A handball goalkeeper is allowed to score goals', TRUE, 1),
('A bowling lane is 18.29 meters long', TRUE, 1),
('The Olympic Games have both Summer and Winter editions', TRUE, 1),
('A baseball game usually consists of nine innings', TRUE, 1),
('A football team is allowed three substitutions per game (standard rules)', TRUE, 1),
('An official tennis ball must be yellow', TRUE, 1),
('A runner can be disqualified for a false start', TRUE, 1),
('A ski jumper lands on flat ground', FALSE, 1),
('An ice hockey game lasts 3 x 20 minutes', TRUE, 1),
('Denmark has hosted the start of the Tour de France', TRUE, 1),
('A football referee uses a whistle and cards to control the game', TRUE, 1);

-- Science category
INSERT INTO categories (`title`, `description`) VALUES
('Science', 'Questions about the nature, human body, our solar system and other general science');

-- Questions in science category
INSERT INTO questions (`text`, `answer`, `category_id`) VALUES
('The Earth revolves around the Sun', TRUE, 2),
('Water boils at 100 degrees Celsius at sea level', TRUE, 2),
('Humans have four lungs', FALSE, 2),
('The chemical symbol for gold is Au', TRUE, 2),
('The speed of light is faster than the speed of sound', TRUE, 2),
('Plants produce oxygen during photosynthesis', TRUE, 2),
('The human body has 206 bones', TRUE, 2),
('The Sun is a planet', FALSE, 2),
('Lightning is hotter than the surface of the Sun', TRUE, 2),
('Sound can travel through a vacuum', FALSE, 2),
('The human heart has four chambers', TRUE, 2),
('The chemical formula for water is H2O', TRUE, 2),
('An atom is larger than a molecule', FALSE, 2),
('Earth is the third planet from the Sun', TRUE, 2),
('Helium is heavier than oxygen', FALSE, 2),
('DNA stands for Deoxyribonucleic Acid', TRUE, 2),
('Electrons are positively charged', FALSE, 2),
('The Great Wall of China can be seen from space with the naked eye', FALSE, 2),
('Humans share about 98% of their DNA with chimpanzees', TRUE, 2),
('Pluto is still officially classified as a planet', FALSE, 2),
('The human brain is made mostly of fat', TRUE, 2),
('Albert Einstein developed the theory of relativity', TRUE, 2),
('The human skeleton renews itself every 10 years', TRUE, 2),
('Venus is the hottest planet in our solar system', TRUE, 2),
('The Pacific Ocean is the largest ocean on Earth', TRUE, 2),
('Carbon dioxide is a compound of carbon and oxygen', TRUE, 2),
('Mars is known as the Blue Planet', FALSE, 2),
('Blood is blue inside the human body', FALSE, 2),
('Gravity was discovered by Isaac Newton', TRUE, 2),
('Humans can distinguish more than a million different colors', TRUE, 2),
('The ozone layer protects us from ultraviolet radiation', TRUE, 2),
('The Moon produces its own light', FALSE, 2),
('The nucleus of an atom contains protons and neutrons', TRUE, 2),
('Energy cannot be created or destroyed', TRUE, 2),
('Sound travels faster in air than in water', FALSE, 2),
('Lightning is a discharge of static electricity', TRUE, 2),
('Humans have five senses', TRUE, 2),
('The chemical symbol for silver is Ag', TRUE, 2),
('Neptune is closer to the Sun than Jupiter', FALSE, 2),
('Oxygen is the most abundant gas in Earth’s atmosphere', FALSE, 2),
('The human liver can regenerate itself', TRUE, 2),
('The Milky Way is a type of galaxy', TRUE, 2),
('All metals are magnetic', FALSE, 2),
('Earth’s atmosphere contains nitrogen and oxygen', TRUE, 2),
('An octopus has three hearts', TRUE, 2),
('The human brain stops growing after birth', FALSE, 2),
('Photosynthesis takes place in the chloroplasts of plant cells', TRUE, 2),
('Diamonds are made mostly of carbon', TRUE, 2),
('The human body is about 60 percent water', TRUE, 2),
('A light year measures time', FALSE, 2),
('The Sun is composed mainly of hydrogen and helium', TRUE, 2),
('Mercury is the smallest planet in our solar system', TRUE, 2),
('Bats are blind', FALSE, 2),
('The largest organ in the human body is the skin', TRUE, 2),
('Atoms are the smallest particles in the universe', FALSE, 2),
('Sharks are mammals', FALSE, 2),
('Water expands when it freezes', TRUE, 2),
('A rainbow is caused by refraction of light', TRUE, 2),
('Human blood comes in four main types', TRUE, 2),
('Earth’s core is mostly made of iron and nickel', TRUE, 2),
('The human eye can detect infrared light', FALSE, 2),
('Mitochondria are known as the powerhouses of the cell', TRUE, 2),
('Carbon is the basis of all known life on Earth', TRUE, 2),
('An eclipse occurs when one celestial body moves into the shadow of another', TRUE, 2),
('The pH scale measures temperature', FALSE, 2),
('The freezing point of water is 0 degrees Celsius', TRUE, 2),
('The largest planet in our solar system is Jupiter', TRUE, 2),
('Viruses can reproduce on their own without a host', FALSE, 2),
('Bees can see ultraviolet light', TRUE, 2),
('The human body has 32 adult teeth', TRUE, 2),
('Light travels in straight lines', TRUE, 2),
('Earth’s gravity keeps the Moon in orbit', TRUE, 2),
('Copper is a good conductor of electricity', TRUE, 2),
('The chemical symbol for sodium is Na', TRUE, 2),
('Plants absorb carbon dioxide and release oxygen', TRUE, 2),
('Humans can breathe underwater without equipment', FALSE, 2),
('The Earth’s magnetic field protects us from solar radiation', TRUE, 2),
('A molecule of oxygen contains one atom', FALSE, 2),
('Earth’s atmosphere has five main layers', TRUE, 2),
('The smallest unit of life is a cell', TRUE, 2),
('Volcanoes are found only on land', FALSE, 2),
('The human stomach produces acid to digest food', TRUE, 2),
('A prism can split white light into colors', TRUE, 2),
('The Moon takes about 30 days to orbit the Earth', TRUE, 2),
('Lightning always strikes the tallest object', FALSE, 2),
('DNA carries genetic information', TRUE, 2),
('Saturn is famous for its rings', TRUE, 2),
('The chemical symbol for iron is Fe', TRUE, 2),
('Earth rotates once every 24 hours', TRUE, 2),
('Humans can live without gravity indefinitely', FALSE, 2),
('Jupiter has more than 70 moons', TRUE, 2),
('The Antarctic is the coldest place on Earth', TRUE, 2),
('Magnets have both north and south poles', TRUE, 2),
('Photosynthesis requires sunlight, carbon dioxide, and water', TRUE, 2),
('The universe is expanding', TRUE, 2),
('Humans can survive without water for weeks', FALSE, 2),
('The boiling point of water decreases at higher altitudes', TRUE, 2),
('All stars are the same size', FALSE, 2),
('Atoms consist of a nucleus surrounded by electrons', TRUE, 2),
('Venus rotates in the opposite direction to most planets', TRUE, 2),
('The Earth’s atmosphere is made mostly of carbon dioxide', FALSE, 2),
('A comet is made of ice and dust', TRUE, 2),
('The Milky Way is the only galaxy in the universe', FALSE, 2);

-- Music category
INSERT INTO categories (`title`, `description`) VALUES
('Music', 'Questions about musicians, musical instruments and popular songs and melodies');

-- Questions for music category
INSERT INTO questions (`text`, `answer`, `category_id`) VALUES
('Elvis Presley is known as the King of Rock and Roll', TRUE, 3),
('The Beatles were a band from the United States', FALSE, 3),
('Beethoven was completely deaf later in his life', TRUE, 3),
('Freddie Mercury was the lead singer of Queen', TRUE, 3),
('The piano has 88 keys', TRUE, 3),
('Michael Jackson released the album Thriller', TRUE, 3),
('The violin is a woodwind instrument', FALSE, 3),
('A standard guitar has six strings', TRUE, 3),
('Mozart was born in Germany', FALSE, 3),
('Jazz originated in the United States', TRUE, 3),
('The saxophone is made of brass', TRUE, 3),
('A drum kit usually includes cymbals', TRUE, 3),
('The Beatles broke up in 1970', TRUE, 3),
('Rap music originated in France', FALSE, 3),
('Beyoncé was a member of Destiny’s Child', TRUE, 3),
('Country music originated in the southern United States', TRUE, 3),
('The flute is played by blowing air into it', TRUE, 3),
('Bob Marley was famous for reggae music', TRUE, 3),
('Taylor Swift started her career as a country singer', TRUE, 3),
('The electric guitar was invented before the acoustic guitar', FALSE, 3),
('The harp is a string instrument', TRUE, 3),
('A symphony is a musical composition for an orchestra', TRUE, 3),
('Drake is a classical pianist', FALSE, 3),
('A metronome is used to keep time in music', TRUE, 3),
('Hip hop and rap are the same genre', FALSE, 3),
('A trumpet is a percussion instrument', FALSE, 3),
('Ed Sheeran is from the United States', FALSE, 3),
('Classical music usually features electric instruments', FALSE, 3),
('The cello is larger than the violin', TRUE, 3),
('A choir consists of singers', TRUE, 3),
('The song Bohemian Rhapsody was recorded by Queen', TRUE, 3),
('A DJ uses turntables to mix music', TRUE, 3),
('A music scale consists of notes', TRUE, 3),
('The clarinet uses a reed to produce sound', TRUE, 3),
('The Rolling Stones are a pop group from Sweden', FALSE, 3),
('Opera combines singing and acting', TRUE, 3),
('Elton John is known for playing the guitar', FALSE, 3),
('The bass guitar has more strings than a regular guitar', FALSE, 3),
('Madonna is often called the Queen of Pop', TRUE, 3),
('A snare drum is part of a drum kit', TRUE, 3),
('Beethoven composed the famous Symphony No 9', TRUE, 3),
('A ukulele is larger than a guitar', FALSE, 3),
('The harmonica is played by blowing and drawing air', TRUE, 3),
('A conductor leads an orchestra', TRUE, 3),
('Heavy metal music often features distorted guitars', TRUE, 3),
('A violin bow is usually made with horsehair', TRUE, 3),
('A remix is a modified version of a song', TRUE, 3),
('The Grammy Awards celebrate achievements in music', TRUE, 3),
('A cappella music uses only instruments', FALSE, 3),
('Jazz music often involves improvisation', TRUE, 3),
('The song Imagine was written by John Lennon', TRUE, 3),
('A triangle is a percussion instrument', TRUE, 3),
('A tuba is the largest brass instrument', TRUE, 3),
('A music album usually contains several songs', TRUE, 3),
('The saxophone was invented by Adolphe Sax', TRUE, 3),
('A string quartet has four musicians', TRUE, 3),
('Michael Jackson was a member of The Rolling Stones', FALSE, 3),
('A piano produces sound by striking strings', TRUE, 3),
('The Beatles’ song Yesterday is one of the most covered songs in history', TRUE, 3),
('Pop music is short for “popular music”', TRUE, 3),
('A conductor uses a stick called a baton', TRUE, 3),
('The French horn belongs to the brass family', TRUE, 3),
('K-pop originated in Japan', FALSE, 3),
('A drum produces sound by vibration of a stretched membrane', TRUE, 3),
('A xylophone is made of wooden bars', TRUE, 3),
('The human voice can be classified into different ranges like soprano and bass', TRUE, 3),
('A guitar pick is used to play the piano', FALSE, 3),
('Reggae music originated in Jamaica', TRUE, 3),
('A vinyl record is played with a needle', TRUE, 3),
('A symphony orchestra includes string, woodwind, brass, and percussion sections', TRUE, 3),
('The song Hey Jude was written by Paul McCartney and John Lennon', TRUE, 3),
('Lady Gaga is known for classical violin performances', FALSE, 3),
('Rap music often includes rhyming lyrics spoken over a beat', TRUE, 3),
('Beethoven wrote the Moonlight Sonata', TRUE, 3),
('A DJ mixer is used to combine different audio sources', TRUE, 3),
('The saxophone is used frequently in jazz music', TRUE, 3),
('Billie Eilish is a country singer', FALSE, 3),
('A banjo has strings', TRUE, 3),
('Drums are tuned using keys and tension rods', TRUE, 3),
('Punk rock originated in the 1970s', TRUE, 3),
('The Beatles’ Abbey Road album features them walking across a crosswalk', TRUE, 3),
('The harp is a percussion instrument', FALSE, 3),
('The first instrument invented was the flute', TRUE, 3),
('A violin has frets', FALSE, 3),
('A microphone converts sound into an electrical signal', TRUE, 3),
('Classical composers include Mozart, Bach, and Beethoven', TRUE, 3),
('Elvis Presley was born in the United Kingdom', FALSE, 3),
('Rock music became popular in the 1950s', TRUE, 3),
('A melody is a sequence of musical notes', TRUE, 3),
('A harmonica is a percussion instrument', FALSE, 3),
('The drums keep the rhythm in a band', TRUE, 3),
('A synthesizer produces electronic sounds', TRUE, 3),
('A baritone voice is higher than a tenor voice', FALSE, 3),
('Jazz musician Louis Armstrong played the trumpet', TRUE, 3),
('A bass guitar plays higher notes than a violin', FALSE, 3),
('The song Shape of You was performed by Ed Sheeran', TRUE, 3),
('The flute belongs to the brass family', FALSE, 3),
('Beethoven was a composer during the Romantic period', FALSE, 3),
('A guitar amplifier makes the sound louder', TRUE, 3),
('Whitney Houston was known for her powerful singing voice', TRUE, 3),
('Classical music originated in the 20th century', FALSE, 3);

-- Movies category
INSERT INTO categories (`title`, `description`) VALUES
('Movies', 'Questions about popular movies, film studios and famous movie stars');

-- Questions for movies category
INSERT INTO questions (`text`, `answer`, `category_id`) VALUES
('The movie Titanic was directed by James Cameron', TRUE, 4),
('The character Forrest Gump was played by Tom Cruise', FALSE, 4),
('The film Jurassic Park was directed by Steven Spielberg', TRUE, 4),
('The movie The Godfather was released in the 1970s', TRUE, 4),
('Avatar was the first movie to use computer graphics', FALSE, 4),
('The character Iron Man is part of the Marvel Cinematic Universe', TRUE, 4),
('Star Wars was created by George Lucas', TRUE, 4),
('The movie Inception stars Leonardo DiCaprio', TRUE, 4),
('The Wizard of Oz was filmed in black and white only', FALSE, 4),
('The movie Jaws features a giant shark', TRUE, 4),
('The character Indiana Jones is an archaeologist', TRUE, 4),
('The movie Casablanca was released in the 1980s', FALSE, 4),
('The main character in The Matrix is named Neo', TRUE, 4),
('The movie Frozen is a live-action film', FALSE, 4),
('The film Pulp Fiction was directed by Quentin Tarantino', TRUE, 4),
('The movie The Dark Knight features the character Joker', TRUE, 4),
('The first Toy Story movie was fully computer animated', TRUE, 4),
('Scarlett Johansson plays Black Widow in Marvel films', TRUE, 4),
('The film E.T. tells the story of an alien stranded on Earth', TRUE, 4),
('The movie Gladiator stars Brad Pitt', FALSE, 4),
('The movie Titanic won multiple Academy Awards', TRUE, 4),
('The movie The Shawshank Redemption is based on a Stephen King story', TRUE, 4),
('The film The Lion King was produced by Pixar', FALSE, 4),
('The main character in Rocky is a boxer', TRUE, 4),
('Jurassic Park features dinosaurs created by cloning', TRUE, 4),
('The movie The Avengers includes characters from DC Comics', FALSE, 4),
('The film The Godfather is about a crime family', TRUE, 4),
('The actor who played Captain America is Chris Evans', TRUE, 4),
('The film The Matrix was released in 1999', TRUE, 4),
('The movie Frozen includes the song Let It Go', TRUE, 4),
('The main character in Toy Story is named Woody', TRUE, 4),
('The film Black Panther takes place in the fictional nation of Wakanda', TRUE, 4),
('The movie Avatar takes place on the planet Mars', FALSE, 4),
('The film Shrek was made by DreamWorks Animation', TRUE, 4),
('The movie The Dark Knight Rises is part of the Batman trilogy', TRUE, 4),
('The movie Finding Nemo is about a lost fish', TRUE, 4),
('The movie Titanic was released in 1997', TRUE, 4),
('The film The Matrix features blue and red pills', TRUE, 4),
('The movie Joker stars Joaquin Phoenix', TRUE, 4),
('The film Interstellar was directed by Christopher Nolan', TRUE, 4),
('The movie Frozen II was released before Frozen', FALSE, 4),
('The film The Godfather Part II won the Academy Award for Best Picture', TRUE, 4),
('The movie Toy Story 3 was released before Toy Story 2', FALSE, 4),
('The movie Avatar used motion capture technology', TRUE, 4),
('The movie The Lion King features talking animals', TRUE, 4),
('The film The Avengers was released before Iron Man', FALSE, 4),
('The movie Titanic is based on a true event', TRUE, 4),
('The movie The Matrix is a musical', FALSE, 4),
('The film Up features a flying house lifted by balloons', TRUE, 4),
('The movie Jaws takes place on Amity Island', TRUE, 4),
('The film The Dark Knight was released in 2008', TRUE, 4),
('The movie Black Panther was the first Marvel film ever made', FALSE, 4),
('The movie Frozen is produced by Disney', TRUE, 4),
('The movie Toy Story features the character Buzz Lightyear', TRUE, 4),
('The film The Godfather Part III was released in the 1990s', TRUE, 4),
('The movie The Shawshank Redemption takes place in a school', FALSE, 4),
('The film Inception involves dreams within dreams', TRUE, 4),
('The movie Titanic stars Leonardo DiCaprio and Kate Winslet', TRUE, 4),
('The movie Forrest Gump includes the line Life is like a box of chocolates', TRUE, 4),
('The movie Gladiator won the Academy Award for Best Picture', TRUE, 4),
('The movie The Matrix features the character Morpheus', TRUE, 4),
('The movie Jaws was released in the 1990s', FALSE, 4),
('The movie The Lion King includes the song Circle of Life', TRUE, 4),
('The film Avatar became the highest-grossing movie of all time upon release', TRUE, 4),
('The movie The Godfather features the line I’m gonna make him an offer he can’t refuse', TRUE, 4),
('The movie Star Wars Episode IV is titled A New Hope', TRUE, 4),
('The movie Titanic features a ship that sinks', TRUE, 4),
('The film Pulp Fiction stars John Travolta and Samuel L Jackson', TRUE, 4),
('The movie Frozen takes place in a kingdom called Arendelle', TRUE, 4),
('The film The Avengers was directed by Steven Spielberg', FALSE, 4),
('The movie The Dark Knight features Batman as the main character', TRUE, 4),
('The movie Finding Nemo includes a character named Dory', TRUE, 4),
('The film Toy Story 4 introduces a character named Forky', TRUE, 4),
('The movie The Matrix features the character Trinity', TRUE, 4),
('The movie Black Panther stars Chadwick Boseman', TRUE, 4),
('The film Titanic is about a warship', FALSE, 4),
('The movie Frozen was released before Tangled', TRUE, 4),
('The movie Jaws features a killer whale', FALSE, 4),
('The film Forrest Gump won several Oscars', TRUE, 4),
('The movie Avatar 2 is titled The Way of Water', TRUE, 4),
('The movie Jurassic Park is based on a book by Michael Crichton', TRUE, 4),
('The film The Godfather was directed by Francis Ford Coppola', TRUE, 4),
('The movie Up was released by Pixar Animation Studios', TRUE, 4),
('The movie Shrek features a talking donkey', TRUE, 4),
('The film The Matrix features virtual reality', TRUE, 4),
('The movie Titanic takes place in space', FALSE, 4),
('The movie Inception includes a spinning top symbol', TRUE, 4),
('The movie Avengers Endgame was released in 2019', TRUE, 4),
('The film Pulp Fiction includes a briefcase with unknown contents', TRUE, 4),
('The movie The Shawshank Redemption is set in a prison', TRUE, 4),
('The movie Frozen II is a sequel', TRUE, 4),
('The movie Joker is part of the Marvel Cinematic Universe', FALSE, 4),
('The film Avatar takes place on a moon called Pandora', TRUE, 4),
('The movie The Lion King features a lion named Simba', TRUE, 4),
('The movie Forrest Gump includes scenes of American history', TRUE, 4),
('The movie Titanic includes the song My Heart Will Go On', TRUE, 4),
('The film The Dark Knight was directed by Christopher Nolan', TRUE, 4),
('The movie Toy Story is a live-action film', FALSE, 4),
('The film Star Wars features a character named Darth Vader', TRUE, 4),
('The movie The Godfather is based on a novel', TRUE, 4),
('The movie Finding Nemo was released before Finding Dory', TRUE, 4),
('The film Pulp Fiction was released before Reservoir Dogs', FALSE, 4);

-- Historical events category
INSERT INTO categories (`title`, `description`) VALUES
('Historical Events', 'Questions about historical events and historical wars');

-- Questions for historical events category
INSERT INTO questions (`text`, `answer`, `category_id`) VALUES
('The American Civil War ended in 1865', TRUE, 5),
('World War I began in 1939', FALSE, 5),
('The Declaration of Independence was signed in 1776', TRUE, 5),
('The Great Fire of London occurred in the 17th century', TRUE, 5),
('The Roman Empire fell in 476 AD', TRUE, 5),
('Christopher Columbus discovered America in 1492', TRUE, 5),
('The Berlin Wall fell in 1989', TRUE, 5),
('World War II ended in 1950', FALSE, 5),
('The French Revolution began in 1789', TRUE, 5),
('The Titanic sank in 1912', TRUE, 5),
('The first human landed on the Moon in 1969', TRUE, 5),
('The Cold War was a direct military conflict between the US and USSR', FALSE, 5),
('The Great Depression began in 1929', TRUE, 5),
('Napoleon Bonaparte was born in France', FALSE, 5),
('The Wright brothers made the first powered flight in 1903', TRUE, 5),
('The Boston Tea Party took place before the American Revolution', TRUE, 5),
('World War II ended with the bombing of Hiroshima and Nagasaki', TRUE, 5),
('The printing press was invented by Johannes Gutenberg', TRUE, 5),
('The Black Death occurred during the 14th century', TRUE, 5),
('The Statue of Liberty was a gift from Germany', FALSE, 5),
('The US entered World War II after the attack on Pearl Harbor', TRUE, 5),
('The first US president was George Washington', TRUE, 5),
('The Great Wall of China was built in the 20th century', FALSE, 5),
('The Battle of Waterloo marked the defeat of Napoleon', TRUE, 5),
('The Renaissance began in Italy', TRUE, 5),
('The fall of Constantinople occurred in 1453', TRUE, 5),
('The first man to orbit Earth was Yuri Gagarin', TRUE, 5),
('The United Nations was founded after World War I', FALSE, 5),
('The American Civil Rights Act was passed in the 1960s', TRUE, 5),
('The assassination of Archduke Franz Ferdinand sparked World War I', TRUE, 5),
('The atomic bomb was first used in 1945', TRUE, 5),
('The Mayflower carried settlers to America in 1620', TRUE, 5),
('The Cold War ended in the early 1990s', TRUE, 5),
('The Vikings came from Spain', FALSE, 5),
('The Great Chicago Fire happened in 1871', TRUE, 5),
('The Roman Colosseum was used for gladiator fights', TRUE, 5),
('The Magna Carta was signed in 1215', TRUE, 5),
('The US bought Alaska from Canada', FALSE, 5),
('Martin Luther King Jr gave his I Have a Dream speech in 1963', TRUE, 5),
('The Berlin Airlift occurred after World War II', TRUE, 5),
('The first World Trade Center attack happened in 2001', FALSE, 5),
('The first US moon landing was part of the Apollo 11 mission', TRUE, 5),
('The American Revolution ended in 1783', TRUE, 5),
('The Great Depression ended with World War II', TRUE, 5),
('Nelson Mandela was imprisoned for over 20 years', TRUE, 5),
('The ancient Egyptians built the Pyramids', TRUE, 5),
('The French Revolution led to the rise of Napoleon', TRUE, 5),
('The Battle of Gettysburg was part of the American Civil War', TRUE, 5),
('The Industrial Revolution began in the United States', FALSE, 5),
('The Declaration of Independence was signed in Philadelphia', TRUE, 5),
('The Berlin Wall divided East and West Berlin', TRUE, 5),
('The Roman Empire conquered all of Asia', FALSE, 5),
('The Wright brothers flew their first airplane in North Carolina', TRUE, 5),
('The Great Fire of Rome happened during the reign of Nero', TRUE, 5),
('The United States dropped two atomic bombs on Japan', TRUE, 5),
('The Reformation began with Martin Luther', TRUE, 5),
('The Cuban Missile Crisis occurred in the 1960s', TRUE, 5),
('The Great Depression began after the 1929 stock market crash', TRUE, 5),
('The first telephone was invented by Alexander Graham Bell', TRUE, 5),
('The Vietnam War ended in 1975', TRUE, 5),
('The Korean War ended in 1990', FALSE, 5),
('The United States entered World War I in 1917', TRUE, 5),
('The Great Wall of China was built to protect against invasions', TRUE, 5),
('The first US president to resign was Richard Nixon', TRUE, 5),
('The ancient city of Pompeii was destroyed by a volcano', TRUE, 5),
('The United Nations headquarters is in New York City', TRUE, 5),
('The Renaissance was a period of cultural rebirth', TRUE, 5),
('The Cold War involved nuclear tension between the US and USSR', TRUE, 5),
('The first airplane was built in Germany', FALSE, 5),
('The Emancipation Proclamation freed enslaved people in the US', TRUE, 5),
('The Roman Empire preceded the Byzantine Empire', TRUE, 5),
('The French Revolution ended with the monarchy restored', FALSE, 5),
('World War II began in 1939', TRUE, 5),
('The Great Fire of London started in a bakery', TRUE, 5),
('The first World War ended in 1918', TRUE, 5),
('The American Civil War began in 1776', FALSE, 5),
('The assassination of John F Kennedy occurred in Dallas', TRUE, 5),
('The United States dropped the first atomic bomb on Tokyo', FALSE, 5),
('The Berlin Wall was built in 1961', TRUE, 5),
('The Roman Empire was founded after the fall of Greece', TRUE, 5),
('The 9 11 attacks happened in 2001', TRUE, 5),
('The Great Depression lasted about a decade', TRUE, 5),
('The French Revolution inspired other revolutions in Europe', TRUE, 5),
('The Cold War began after World War II', TRUE, 5),
('The Wright brothers were American inventors', TRUE, 5),
('The Titanic sank on its first voyage', TRUE, 5),
('The Roman Empire was ruled by emperors', TRUE, 5),
('The United States declared independence from France', FALSE, 5),
('World War I ended with the Treaty of Versailles', TRUE, 5),
('The Industrial Revolution began in Britain', TRUE, 5),
('The Great Pyramid of Giza is one of the Seven Wonders of the Ancient World', TRUE, 5),
('The US Civil Rights Movement took place mainly in the 1960s', TRUE, 5),
('The atomic bomb was first tested in New Mexico', TRUE, 5),
('The Berlin Wall symbolized the division between capitalism and communism', TRUE, 5),
('The Vietnam War was fought between North and South Vietnam', TRUE, 5),
('The French Revolution began before the American Revolution', FALSE, 5),
('The first US president was Abraham Lincoln', FALSE, 5),
('The Renaissance led to major advancements in art and science', TRUE, 5),
('The Great Fire of Chicago destroyed most of the city', TRUE, 5),
('The moon landing occurred during the Cold War', TRUE, 5),
('The Boston Tea Party involved dumping tea into the ocean', TRUE, 5),
('The fall of the Berlin Wall marked the end of the Cold War', TRUE, 5),
('The Titanic sank after hitting an iceberg', TRUE, 5),
('The French Revolution abolished the monarchy in France', TRUE, 5);
