spring:
  application:
    name: "True/False Game API"
    description: "An API for providing True/False questions in different categories."
    version: 1
    api-key: ${API_KEY}
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
